#ifndef __CONFIG_H__
#define __CONFIG_H__

/*!
 * \brief Represents all possible opcode understood by the radio
 */
typedef enum RadioCommands_u
{
    RADIO_GET_STATUS = 0xC0,
    RADIO_WRITE_REGISTER = 0x18,
    RADIO_READ_REGISTER = 0x19,
    RADIO_WRITE_BUFFER = 0x1A,
    RADIO_READ_BUFFER = 0x1B,
    RADIO_SET_SLEEP = 0x84,
    RADIO_SET_STANDBY = 0x80,
    RADIO_SET_FS = 0xC1,
    RADIO_SET_TX = 0x83,
    RADIO_SET_RX = 0x82,
    RADIO_SET_RXDUTYCYCLE = 0x94,
    RADIO_SET_CAD = 0xC5,
    RADIO_SET_TXCONTINUOUSWAVE = 0xD1,
    RADIO_SET_TXCONTINUOUSPREAMBLE = 0xD2,
    RADIO_SET_PACKETTYPE = 0x8A,
    RADIO_GET_PACKETTYPE = 0x03,
    RADIO_SET_RFFREQUENCY = 0x86,
    RADIO_SET_TXPARAMS = 0x8E,
    RADIO_SET_CADPARAMS = 0x88,
    RADIO_SET_BUFFERBASEADDRESS = 0x8F,
    RADIO_SET_MODULATIONPARAMS = 0x8B,
    RADIO_SET_PACKETPARAMS = 0x8C,
    RADIO_GET_RXBUFFERSTATUS = 0x17,
    RADIO_GET_PACKETSTATUS = 0x1D,
    RADIO_GET_RSSIINST = 0x1F,
    RADIO_SET_DIOIRQPARAMS = 0x8D,
    RADIO_GET_IRQSTATUS = 0x15,
    RADIO_CLR_IRQSTATUS = 0x97,
    RADIO_CALIBRATE = 0x89,
    RADIO_SET_REGULATORMODE = 0x96,
    RADIO_SET_SAVECONTEXT = 0xD5,
    RADIO_SET_AUTOTX = 0x98,
    RADIO_SET_AUTOFS = 0x9E,
    RADIO_SET_LONGPREAMBLE = 0x9B,
    RADIO_SET_UARTSPEED = 0x9D,
    RADIO_SET_RANGING_ROLE = 0xA3,
} RadioCommands_t;

#endif /* __CONFIG_H__ */
